[package]
name = "taskboard-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum = "=0.7.9"
chrono.workspace = true
include_dir = "=0.7.4"
mime_guess = "=2.0.5"
rand = "=0.8.5"
serde.workspace = true
serde_json.workspace = true
taskboard-application = { path = "../application" }
taskboard-core = { path = "../core" }
thiserror.workspace = true
tokio = { workspace = true, features = ["net", "signal", "io-util", "sync"] }
tower = { version = "=0.4.13", default-features = false, features = ["util"] }
tower-http = { version = "=0.5.2", features = ["fs"] }
uuid.workspace = true

[dev-dependencies]
reqwest = { version = "=0.12.12", default-features = false, features = ["json", "rustls-tls"] }
tempfile = "=3.19.1"
taskboard-store-sqlite = { path = "../store-sqlite" }
